In [1]:
import dask.dataframe as dd

df = dd.read_csv('cars.csv',delimiter=';')
df = df[df.price <= 40000]
df = df.nlargest(10, 'price')

df.compute()

,brand,model,year,km,power,price
LEXUS,NX,NX 300h 4WD,2015,39 816,Essence / Courant Électrique,31980
RENAULT,TALISMAN,Talisman dCi 130 Energy,2015,24416,Diesel,19490
RENAULT,ESPACE,Espace dCi 160 Energy Twin Turbo,2015,51800,Diesel,18990
BMW,SERIE 2,Active Tourer 218d 150 ch,2015,49819,Diesel,18900
RENAULT,KOLEOS,Koleos 2.0 dCi 150,2015,62731,Diesel,15990
RENAULT,KOLEOS,Koleos 2.0 dCi 175,2015,67263,Diesel,15990
NISSAN,QASHQAI,Qashqai 1.2 DIG-T 115,2015,58998,Essence Sans Plomb,15989
RENAULT,KADJAR,Kadjar dCi 110 Energy eco²,2015,54525,Diesel,15979
NISSAN,QASHQAI,Qashqai 1.6 dCi 130 Stop/Start,2015,75120,Diesel,15760
RENAULT,TALISMAN,Talisman dCi 130 Energy,2015,65724,Diesel,14990